"""empty message

Revision ID: 1bcc87997a1c
Revises: 4cd5bb2931c
Create Date: 2015-05-09 21:56:32.351662

"""

# revision identifiers, used by Alembic.
revision = '1bcc87997a1c'
down_revision = '4cd5bb2931c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.VARCHAR(length=80), nullable=False))
    ### end Alembic commands ###
